"""empty message

Revision ID: 25029a1c795f
Revises: 
Create Date: 2025-06-06 14:45:33.306595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25029a1c795f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###
