"""empty message

Revision ID: 2cf9b9c6d30e
Revises: 25029a1c795f
Create Date: 2025-06-12 13:51:00.824079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cf9b9c6d30e'
down_revision = '25029a1c795f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('author_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('image_path', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               nullable=True)
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['category_id'])
        batch_op.drop_column('title')
        batch_op.drop_column('author')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('image_path', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('image_path')
        batch_op.drop_column('description')

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('description',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('category_id')
        batch_op.drop_column('image_path')
        batch_op.drop_column('status')
        batch_op.drop_column('author_name')
        batch_op.drop_column('book_name')

    # ### end Alembic commands ###
