"""Add return_requested to borrow_requests

Revision ID: fed74edaf1ff
Revises: 2cf9b9c6d30e
Create Date: 2025-06-19 00:36:44.291618
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'fed74edaf1ff'
down_revision = '2cf9b9c6d30e'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrow_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('return_requested', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrow_requests', schema=None) as batch_op:
        batch_op.drop_column('return_requested')
    # ### end Alembic commands ###